### ISSUE TITLE
Call to `f32::exp()` prevents crate to compile on `no_std`

### ISSUE THREAD

**Issue by eflukx** [mjaakkol/sgpc3-rs#1]
The `f32::exp()` method is part of the f32 primitive in `std` and unfortunately not part of `core`. It breaks compilation on my target (Arm Cortex, nRF52833). Removing the call to `.exp()` fixes compilation, so it seems this is the only place where a `std` function is called. 

```
   Compiling sgpc3 v0.0.2
error[E0599]: no method named `exp` found for type `f32` in the current scope
   --> /home/eflukx/.cargo/registry/src/github.com-1ecc6299db9ec823/sgpc3-0.0.2/src/lib.rs:415:69
    |
415 |             * (rh * 61.12_f32 * ((17.62_f32 * t / (243.12_f32 + t)).exp()) / (273.15_f32 + t));
    |                                                                     ^^^ method not found in `f32`
```

**Comment by eflukx** [comment]
Hmm.. `unsafe { core::intrinsics::expf32(1.4f32) }` _does_ work on my target, but is only supported on nightly rust (and probably not the way to go anyway).

Probably need to add a dependency on `num-traits` for `no_std` environments...(?)

**Comment by mjaakkol** [comment]
I think there are two high-level paths to fix this issue.

1) Find and implement an alternative way of calculating exp() that doesn't rely on std
2) Approximate the conversion in limited temperature range without exp operation while trying to keep relatively good accuracy (should be doable)

The implementation #1 and #2 could be the adjusted if Rust starts to support the operation (https://blog.rust-lang.org/inside-rust/2022/02/22/compiler-team-ambitions-2022.html#compiler-backend-aspirations-%EF%B8%8F-)

If you have other ideas or preference, I'm all ears

**Comment by eflukx** [comment]
Hi, Thanks for the quick response!

> 1. Find and implement an alternative way of calculating exp() that doesn't rely on std

Tried to use `powf()`, but.. you guessed it: not available either.. 😢 

> 2. Approximate the conversion in limited temperature range without exp operation while trying to keep relatively good accuracy (should be doable)

Yeah sure, we can approximate exp(), maybe linear interpolation of a LUT or something. For me this is too much hassle currently, I fixed it on my fork by depending on `num-traits` (and `libm` by proxy), which looks like it is the way to go if you want proper math support on embedded targets anyway. :)

Will send a PR in a moment.

**Comment by mjaakkol** [comment]
This is perfect fix. I don't think anybody should be "bounding" the sensor to justify extra optimization hassle. This is a clean and beautiful fix.

**Comment by eflukx** [comment]
I see you released a new version to crates.io already.
Cheers mate! 🍺

**Comment by eflukx** [comment]
Oops think I cheered to that a bit too soon.. 😨 

The `#[cfg(no_std)]` conditional gate does not seem to do the job, probably we'll need to add a "std" (or "no_std") feature to the crate. See discussion on this topic here https://github.com/rust-lang/rust/issues/42190

Btw. I haven't tested it on a `std` environment with the `num_traits` crate, but I think it is expected to work on a `std` env just as well. So don't know if a feature gate is needed. Anyway when adding one, we can skip the dependency on `num-traits` altogether, which increases overall compilation speed.. always a good thing !😄
